### ISSUE TITLE
How to retrieve all the wallets generated from seed phrase?

### ISSUE THREAD

**Issue by 0xharkirat** [keshav-exe/projekt-kosh#2]
I am also implementing the solution. When I was testing your implementation, when I used the recovery phrase & tries to retrieve wallets, it only returns the first wallet?

**Comment by keshav-exe** [comment]
https://github.com/keshav-exe/projekt-kosh/blob/main/components/WalletGenerator.tsx#L116

here check this out I have two two functions for wallet generation right now, will merge them shortly.

**Comment by 0xharkirat** [comment]
I found the first one, on which line is the second function?

**Comment by 0xharkirat** [comment]
anyways, I have found my answer. Great Work, Btw. You can close this if you want.
